---
title: "SentimenAnalisisReviewAplikasiTraveloka"
author: "Muhammad Rizki Firmansyah/123200064 & Ardhian Kusumayuda/123200144"
date: "2022-11-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tm)
library(wordcloud2)
library(vroom)
library(here)
library(RTextTools)
library(dplyr)
library(wordcloud)
library(shiny)
library(ggplot2)
library(plotly)
```

```{r Data Cleaning}
d <- vroom(here('ReviewTraveloka-3000.csv'))
ulasan <- d$content
ulasan1 <- Corpus(VectorSource(ulasan))
removeURL <- function(x) gsub("http[^[:space:]]*", "", x)
reviewclean <- tm_map(ulasan1, removeURL)
removeNL <- function(y) gsub("\n", " ", y)
reviewclean <- tm_map(ulasan1, removeNL)
replacecomma <- function(y) gsub(",", "", y)
reviewclean <- tm_map(reviewclean, replacecomma)
removetitik2 <- function(y) gsub(":", "", y)
reviewclean <- tm_map(reviewclean, removetitik2)
removetitikkoma <- function(y) gsub(";", " ", y)
reviewclean <- tm_map(reviewclean, removetitikkoma)
removetitik3 <- function(y) gsub("p...", "", y)
reviewclean <- tm_map(reviewclean, removetitik3)
removeamp <- function(y) gsub("&amp", "", y)
reviewclean <- tm_map(reviewclean, removeamp)
removeUN <- function(z) gsub("@\\w+", "", z)
reviewclean <- tm_map(reviewclean, removeUN)
remove.all <- function(xy) gsub("[^[:alpha:][:space:]]*", "", xy)
reviewclean <- tm_map(reviewclean, remove.all)
reviewclean <- tm_map(reviewclean, removePunctuation)
reviewclean <- tm_map(reviewclean, tolower)
MyStopWords <- readLines("stopwords-id.txt")
reviewclean <- tm_map(reviewclean,removeWords,MyStopWords)


dataframe <- data.frame(text=unlist(sapply(reviewclean,`[`)),stringsAsFactors = F)
View(dataframe)
write.csv(dataframe,file = 'ReviewTraveloka-Clean.csv')
```

```{r Sentimen Analisis Naive Bayes Classifier}
library(e1071) #Naive Bayes
library(caret) #Klasifikasi Data
library(syuzhet) #membaca fungsi get_nrc

data_traveloka <- read.csv("ReviewTraveloka-Clean.csv", stringsAsFactors =  FALSE)
review <- as.character(data_traveloka$text) #merubah string menjadi char
s <- get_nrc_sentiment(review)

review_combine <- cbind(data_traveloka$text,s) #klasifikasi data
par(mar=rep(3,4))
a <- barplot(colSums(s), col=rainbow(10),ylab='count',main='Sentiment Analisis')
brplt <- a
```
Memanggil library tambahan yang akan digunakan untuk penggunaan corpus dalam proses cleaning data selanjutnya, Mengatur seed generator bilangan acak R, yang berguna untuk membuat simulasi atau objek acak yang dapat direproduksi.

```{r}
require (corpus)
df<-read.csv("ReviewTraveloka-Clean.csv",stringsAsFactors = FALSE)
glimpse(df)
set.seed(20)
df<-df[sample(nrow(df)),]
df<-df[sample(nrow(df)),]
glimpse(df)
corpus<-Corpus(VectorSource(df$text))
corpus
inspect(corpus[1:10])

#membersihkan data data yang tidak dibutuhkan 
corpus.clean<-corpus%>%
    tm_map(content_transformer(tolower))%>%
    tm_map(removePunctuation)%>%
    tm_map(removeNumbers)%>%
    tm_map(removeWords, c("yang", "dan", "dari", "aasi", "ini", "kita", "untuk" ,"nya"))%>%
    tm_map(removeWords,stopwords(kind="en"))%>%
    tm_map(stripWhitespace)
dtm<-DocumentTermMatrix(corpus.clean)
inspect(dtm[1:10,1:20])
df.train<-df[1:50,]
df.test<-df[51:100,]                                            
dtm.train<-dtm[1:50,]
dtm.test<-dtm[51:100,]
corpus.clean.train<-corpus.clean[1:50]
corpus.clean.test<-corpus.clean[51:100]
dim(dtm.train)
fivefreq<-findFreqTerms(dtm.train,5)
length(fivefreq)
dtm.train.nb<-DocumentTermMatrix(corpus.clean.train,control = list(dictionary=fivefreq))
#dim(dtm.train.nb)
dtm.test.nb<-DocumentTermMatrix(corpus.clean.test,control = list(dictionary=fivefreq))
dim(dtm.test.nb)
 
convert_count <- function(x){
    y<-ifelse(x>0,1,0)
    y<-factor(y,levels=c(0,1),labels=c("no","yes"))
    y
}
trainNB<-apply(dtm.train.nb,2,convert_count)
testNB<-apply(dtm.test.nb,1,convert_count)
wordcloud(corpus.clean,min.freq = 4,max.words=100,random.order=F,colors=brewer.pal(8,"Dark2"))
kalimat2<-read.csv("ReviewTraveloka-Clean.csv",header=TRUE)

#skoring
kata.positif <- scan("kata-positif.txt",what="character",comment.char=";")
kata.negatif <- scan("kata-negatif.txt",what="character",comment.char=";")
score.sentiment = function(kalimat2, kata.positif, kata.negatif,
                           .progress='none')
{
  require(plyr)
  require(stringr)
  scores = laply(kalimat2, function(kalimat, kata.positif,
                                    kata.negatif) {
    kalimat = gsub('[[:punct:]]', '', kalimat)
    kalimat = gsub('[[:cntrl:]]', '', kalimat)
    kalimat = gsub('\\d+', '', kalimat)
    kalimat = tolower(kalimat)
    list.kata = str_split(kalimat, '\\s+')
    kata2 = unlist(list.kata)
    positif.matches = match(kata2, kata.positif)
    negatif.matches = match(kata2, kata.negatif)
    positif.matches = !is.na(positif.matches)
    negatif.matches = !is.na(negatif.matches)
    score = sum(positif.matches) - (sum(negatif.matches))
    return(score)
  }, kata.positif, kata.negatif, .progress=.progress )
  scores.df = data.frame(score=scores, text=kalimat2)
  return(scores.df)}
hasil = score.sentiment(kalimat2$text, kata.positif, kata.negatif)

#mengubah nilai score menjadi sentimen
hasil$klasifikasi<- ifelse(hasil$score<0, "Negatif",ifelse(hasil$score==0,"Netral","Positif"))

hasil$klasifikasi

#menukar urutan baris
data <- hasil[c(3,1,2)]

#View(data)
write.csv(data, file = "datalabel.csv")

```

```{r}
library(dplyr)

class_sentiment <- data.frame(negative=s$negative,positive=s$positive)
klasifikasi <- mutate(class_sentiment, text_sentiment = ifelse((class_sentiment$negative != class_sentiment$positive),
                                                               ifelse(class_sentiment$negative!=0,print("negative"),
                                                                      print("positive")),print("neutral")))
data_traveloka <- data.frame(text=review,s=klasifikasi$text_sentiment)
View(data_traveloka)
```
Visualisasi Data dengan GUI Shiny

```{r}
library(syuzhet) #membaca fungsi get_nrc
dataLabel<- read.csv("datalabel.csv")
ui <- fluidPage(
    titlePanel("Sentimen Analisis Ulasan/Review Aplikasi Traveloka"),
        mainPanel(
            
            tabsetPanel(type = "tabs",
                        tabPanel("BoxPlot", plotOutput("scatterplot")), 
                        # Plot
                        tabPanel("Data", DT::dataTableOutput('tbl1')),
                        #Sentimen Analysis
                        tabPanel("Sentiment Analysis", DT::dataTableOutput("sentiment")),
                        # WordCloud
                        tabPanel("Wordcloud", plotOutput("Wordcloud"))
                        )
        )
    )
# SERVER
server <- function(input, output) {
    
    # Output Data
    output$tbl1 = DT::renderDataTable({
        DT::datatable(dataLabel, options = list(lengthChange = FALSE))
    })
    
      output$sentiment <- DT::renderDataTable({
    DT::datatable(data_traveloka, options= list(lengthChange = FALSE))

  })
    
    output$scatterplot <- renderPlot({produk_dataset<-read.csv("ReviewTraveloka-Clean.csv",stringsAsFactors = FALSE)
      review <-as.character(produk_dataset$text)
      s<-get_nrc_sentiment(review)
      review_combine<-cbind(produk_dataset$text,s)
      par(mar=rep(3,4))
      barplot(colSums(s),col=rainbow(10),ylab='count',main='Sentimen Analisis Ulasan/Review Aplikasi Traveloka')
          }, height=400)
    output$Wordcloud <- renderPlot({
     set.seed(20)
      df<-df[sample(nrow(df)),]
      df<-df[sample(nrow(df)),]
      glimpse(df)
      inspect(dtm[1:10,1:20])
      df.train<-df[1:50,]
      df.test<-df[51:100,]
      dtm.train<-dtm[1:50,]
      dtm.test<-dtm[51:100,]
      dim(dtm.train)
      fivefreq<-findFreqTerms(dtm.train,5)
      length(fivefreq)
      dtm.train.nb<-DocumentTermMatrix(corpus.clean.train,control = list(dictionary=fivefreq))
      #dim(dtm.train.nb)
      dtm.test.nb<-DocumentTermMatrix(corpus.clean.test,control = list(dictionary=fivefreq))
      dim(dtm.test.nb)
 
convert_count <- function(x){
    y<-ifelse(x>0,1,0)
    y<-factor(y,levels=c(0,1),labels=c("no","yes"))
    y
}
trainNB<-apply(dtm.train.nb,2,convert_count)
testNB<-apply(dtm.test.nb,1,convert_count)
wordcloud(corpus.clean,min.freq = 4,max.words=100,random.order=F,colors=brewer.pal(8,"Dark2"))
  })
}
shinyApp(ui = ui, server = server)
```

