# -*- coding: utf-8 -*-
"""Scrapping-Traveloka.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12jNaDgA1wT8Psl7wYPYVlxJABNXCbGIj
"""

!pip install google-play-scraper

from google.colab import drive
drive.mount('/content/drive')

from google_play_scraper import app
import pandas as pd #untukmembuatdataframe
import numpy as np #untukoperasivektroataumatriks

from google_play_scraper import Sort, reviews_all
us_reviews = reviews_all(
    'com.traveloka.android',
    sleep_milliseconds=0, # defaults to 0
    lang='id', # defaults to 'en'
    country='id', # defaults to 'us'
    sort=Sort.NEWEST, # defaults to Sort.MOST_RELEVANT
    count=2500,
)

df_data = pd.DataFrame(np.array(us_reviews),columns=['review'])
df_data = df_data.join(pd.DataFrame(df_data.pop('review').tolist()))
df_data.head()

len(df_data.index)

df_data[['userName', 'score','at', 'content']].head()

review = df_data[['userName', 'score','at', 'content']]
sorted_df = review.sort_values(by='at', ascending=False) 
sorted_df.head()

ss = sorted_df[['userName', 'score','at', 'content']]

ss.head()

ss.to_csv("ReviewTraveloka.csv", index = False)